

################## LOGIN / USER ####################

### REGISTER/CREATE USER
POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
  "firstName": "JAnn",
  "lastName": "Poudel",
  "email": "aj@w.com",
  "password": "vangunneR@45"
}

### LOGIN 
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "aj@w.com",
  "password": "vangunneR45"
}

### LOGOUT
PUT http://localhost:5000/api/v1/auth/logout
Content-Type: application/json

{
  "accessJwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwQHcuY29tIiwiX2lkIjoiNjIwMjVkYzY5NTgwOTdlYTI4ZmQyOTg5IiwiaWF0IjoxNjQ0MzIzODU2LCJleHAiOjE2NDYwNTE4NTZ9.wIgFe2eA32BJToD4EQWHriNSkuqIWzN1SnwEOVUuXPI",
  "refreshJwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwQHcuY29tIiwiaWF0IjoxNjQ0MzIzODU2LCJleHAiOjE2NDY5MTU4NTZ9.SUKKxd5eN84-BLElp7THaWP95nFEzyvbUUAAo2AwVrc"
}

### GET USER BY EMAIL
GET http://localhost:5000/api/v1/user/byemail
Content-Type: application/json

{
  "email" : "aj@w.com"
}

### GET ALL USERS
GET http://localhost:5000/api/v1/user/all


### SEND OTP
POST http://localhost:5000/api/v1/auth/otp
Content-Type: application/json

{
  "email": "aj@w.com"
}

### UPDATE PASSWORD
PATCH  http://localhost:5000/api/v1/auth/password
Content-Type: application/json

{
  "pin": 79546,
  "email": "aj@w.com",
  "password" : "vangunneR@45"
}

### UPDATE PASSWORD VIA SETTINGS
PATCH http://localhost:5000/api/v1/auth/update-password
Content-Type: application/json

{
  "newPassword": "vangunneR45",
  "email" : "aj@w.com"
}

################## PRODUCT ####################

### CREATE PRODUCT
POST http://localhost:5000/api/v1/product
Content-Type: application/json

{
  "isAvailable": true,
  "title": "Iphone 7plus",
  "price": 1005,
  "description": "The iPhone 7 and iPhone 7 Plus are smartphones designed, developed, and marketed by Apple Inc. They are the tenth generation of the iPhone.",
  "quantity": 105,
  "images": [],
  "onSale": false,
  "categories": "Electronice",
  "salePrice": 0,
  "saleEndDate": ""
}

### UPDATE PRODUCT
PUT http://localhost:5000/api/v1/product/6204b24a2ae69a32a076dd71
Content-Type: application/json

{
  "isAvailable": true,
  "name": "Samsung Galaxy",
  "price": 1045.95,
  "description": "Samsung Galaxy is a series of computing and mobile computing devices that are designed, manufactured and marketed by Samsung Electronics.",
  "qty": 15,
  "images": [],
  "onSale": true,
  "categories": "Electronice",
  "salePrice": 899.99,
  "saleEndDate": "2022/03/01"
  }

### GET SINGLE PRODUCT BY ID
GET http://localhost:5000/api/v1/product/62247ae3d6d4c99ddcd5ce7f

### GET ALL PRODUCTS
GET http://localhost:5000/api/v1/product?category=Electronics

### DELETE PRODUCT BY ID
DELETE http://localhost:5000/api/v1/product/6212dd1ff33d4356f09e3406



################## CATEGORY ####################

### CREATE CATEGORY
POST http://localhost:5000/api/v1/category
Content-Type: application/json

{
  "newCategory": "Footwear",
  "parentCategory": null
}

### GET ALL CATEGORY
GET http://localHost:5000/api/v1/category


### GET SINGLE CATEGORY
GET http://localHost:5000/api/v1/category/623a8cea92388753ec0b9c03

### UDPATE CATEGORY
PUT http://localhost:5000/api/v1/category
Content-Type: application/json

{
  "_id":"6204b601d78ae6cc4b2599f7",
  "name" : "Technology",
  "parentCat" : null
}

### DELETE CATEGORY
DELETE  http://localhost:5000/api/v1/category 
Content-Type: application/json

{
  "_id":"6204b601d78ae6cc4b2599f7",
  "name" : "Technology",
  "parentCat" : null
}


################## CLIENT ENDPOINT ####################


### GET ALL CLIENTS
GET http://localhost:5000/api/v1/client

### GET CLIENTS BY ID
GET http://localhost:5000/api/v1/client/62274da7bfc6939716a4fcdd

### GET CLIENT STATS
GET http://localhost:5000/api/v1/client/clientInfo

### GET MONTHLY INCOME
GET http://localHost:5000/api/v1/order/income

### GET OVERALL INCOME
GET http://localHost:5000/api/v1/order/overall