

################## LOGIN / USER ####################

### REGISTER/CREATE USER
POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
  "firstName": "JAnn",
  "lastName": "Poudel",
  "email": "aj@w.com",
  "password": "vangunneR@45"
}

### LOGIN 
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "aj@w.com",
  "password": "vangunneR45"
}

### LOGOUT
PUT http://localhost:5000/api/v1/auth/logout
Content-Type: application/json

{
  "accessJwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwQHcuY29tIiwiX2lkIjoiNjIwMjVkYzY5NTgwOTdlYTI4ZmQyOTg5IiwiaWF0IjoxNjQ0MzIzODU2LCJleHAiOjE2NDYwNTE4NTZ9.wIgFe2eA32BJToD4EQWHriNSkuqIWzN1SnwEOVUuXPI",
  "refreshJwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwQHcuY29tIiwiaWF0IjoxNjQ0MzIzODU2LCJleHAiOjE2NDY5MTU4NTZ9.SUKKxd5eN84-BLElp7THaWP95nFEzyvbUUAAo2AwVrc"
}

### GET USER BY EMAIL
GET http://localhost:5000/api/v1/user/byemail
Content-Type: application/json

{
  "email" : "aj@w.com"
}

### GET ALL USERS
GET http://localhost:5000/api/v1/user/all


### SEND OTP
POST http://localhost:5000/api/v1/auth/otp
Content-Type: application/json

{
  "email": "aj@w.com"
}

### UPDATE PASSWORD
PATCH  http://localhost:5000/api/v1/auth/password
Content-Type: application/json

{
  "pin": 79546,
  "email": "aj@w.com",
  "password" : "vangunneR@45"
}

### UPDATE PASSWORD VIA SETTINGS
PATCH http://localhost:5000/api/v1/auth/update-password
Content-Type: application/json

{
  "newPassword": "vangunneR45",
  "email" : "aj@w.com"
}

################## PRODUCT ####################


### CREATE PRODUCT
POST http://localhost:5000/api/v1/product
Content-Type: application/json

{
  "isAvailable": true,
  "name": "Nike Shoes",
  "price": 75.95,
  "description": "Perfect shoes for men",
  "qty": 1,
  "images": [],
  "categories": "Clothing",
  "salePrice": 50.2,
  "saleEndDate": 2022-03-20
  }

### UPDATE PRODUCT
PUT http://localhost:5000/api/v1/product/620323a8b08232e008dd863e
Content-Type: application/json

{
  "isAvailable": true,
  "name": "Men's Short Sleeve Henley Tee",
  "desc": "Classic fit  neck",
  "price": 75.95,
  "qty": 1,
  "images": [],
  "categories": "Clothing",
  "onSale": true,
  "salePrice": 50.96,
  "saleEndDate": "2022-19-02T13:34:00.000",
  }

### GET SINGLE PRODUCT / PRODUCT BY ID
GET http://localhost:5000/api/v1/product